name: "Piconvert"
description: "Convert pictures to other formats. Supports ai, cdr, vsd, pdf, and more formats."
author: "JacobLinCool"

inputs:
    src:
        description: "Source path. If it's a directory, all files matched selected import types in it and its subdirectories will be converted."
        required: false
        default: "pictures"
    dist:
        description: "Output directory."
        required: false
        default: "piconvert"
    inputs:
        description: "Import (input) formats. Supports: ai,cdr,vsd,pdf,jpg,jpeg,png,gif,bmp"
        required: false
        default: "ai"
    outputs:
        description: "Export (output) formats. Supports: svg,png,ps,eps,pdf,emf,wmf,xaml"
        required: false
        default: "svg,png"

runs:
    using: "composite"
    steps:
        - name: Prepare Environment
          shell: bash
          run: |
              sudo add-apt-repository ppa:inkscape.dev/stable && sudo apt update && sudo apt install -y inkscape

        - name: Install Piconvert
          shell: bash
          run: |
              sudo npm i -g piconvert

        - name: Run Piconvert
          shell: bash
          run: |
              sudo piconvert -v -f "${{ inputs.formats }}" -o "${{ inputs.dist }}" "${{ inputs.source }}"

branding:
    icon: image
    color: purple
