name: "Piconvert"
description: "Convert pictures to other formats. Supports ai, cdr, vsd, pdf, and more formats."
author: "JacobLinCool"

inputs:
    src:
        description: "Source path. If it's a directory, all files matched selected import types in it and its subdirectories will be converted."
        required: false
        default: "pictures"
    dist:
        description: "Output directory."
        required: false
        default: "piconvert"
    inputs:
        description: "Import (input) formats. Supports: ai,cdr,vsd,pdf,jpg,jpeg,png,gif,bmp"
        required: false
        default: "ai"
    outputs:
        description: "Export (output) formats. Supports: svg,png,ps,eps,pdf,emf,wmf,xaml"
        required: false
        default: "svg,png"
    force:
        description: "Overwrite existing files"
        required: false
        default: "false"
    silent:
        description: "Silent mode, no output"
        required: false
        default: "false"
    verbose:
        description: "Verbose mode, print all Inkscape output"
        required: false
        default: "false"

runs:
    using: "composite"
    steps:
        - name: Install Piconvert
          shell: bash
          run: |
              sudo npm i -g piconvert

        - name: Install Dependencies
          shell: bash
          run: |
              sudo piconvert install

        - name: Run Piconvert
          shell: bash
          run: |
              sudo piconvert -i "${{ inputs.inputs }}" -o "${{ inputs.outputs }}" -d "${{ inputs.dist }}" ${{ inputs.force == 'true' && '-f' || '' }} ${{ inputs.silent == 'true' && '-s' || '' }} ${{ inputs.verbose == 'true' && '-v' || '' }} "${{ inputs.src }}"

branding:
    icon: image
    color: purple
